import type { PlutusVersion } from "./cardanoCli";

export function generateEvolutionSdkSnippet(input: {
  cborHex: string;
  plutusVersion?: PlutusVersion;
  exportName: string;
  networkId: number;
  includeAddressAndHashes: boolean;
}): string {
  const plutusModule = input.plutusVersion ?? "PlutusV2";

  return (
    `// Generated by aiken-devtools-mcp (tool: aiken_codegen_evolution_sdk)\n` +
    `// Source repo: https://github.com/IntersectMBO/evolution-sdk\n\n` +
    `import { Schema } from "effect";\n` +
    `import * as Address from "@evolution-sdk/evolution/Address";\n` +
    `import * as Bytes from "@evolution-sdk/evolution/Bytes";\n` +
    `import * as ScriptHash from "@evolution-sdk/evolution/ScriptHash";\n` +
    `import * as PlutusV1 from "@evolution-sdk/evolution/PlutusV1";\n` +
    `import * as PlutusV2 from "@evolution-sdk/evolution/PlutusV2";\n` +
    `import * as PlutusV3 from "@evolution-sdk/evolution/PlutusV3";\n\n` +
    `export const ${input.exportName}CborHex = "${input.cborHex}";\n` +
    `export const ${input.exportName}Script = new ${plutusModule}.${plutusModule}({ bytes: Bytes.fromHex(${input.exportName}CborHex) });\n` +
    (input.includeAddressAndHashes
      ? `\nexport const ${input.exportName}ScriptHash = ScriptHash.fromScript(${input.exportName}Script);\n` +
        `export const ${input.exportName}PolicyIdHex = ScriptHash.toHex(${input.exportName}ScriptHash);\n` +
        `\n// Enterprise address (no staking credential)\n` +
        `export const ${input.exportName}AddressStruct = new Address.Address({\n` +
        `  networkId: ${input.networkId},\n` +
        `  paymentCredential: ${input.exportName}ScriptHash,\n` +
        `  stakingCredential: undefined\n` +
        `});\n` +
        `export const ${input.exportName}AddressBech32 = Schema.encodeSync(Address.FromBech32)(${input.exportName}AddressStruct);\n`
      : "")
  );
}

export function generateLucidEvolutionSnippet(input: {
  cborHex: string;
  plutusVersion?: PlutusVersion;
  exportName: string;
  kind: "spending" | "minting";
  includeAddressOrPolicyId: boolean;
}): string {
  const importTypes = input.kind === "minting" ? "MintingPolicy" : "SpendingValidator";
  const asType = input.kind === "minting" ? "MintingPolicy" : "SpendingValidator";

  const derivationLine =
    input.kind === "minting"
      ? `export const ${input.exportName}Id = lucid.utils.mintingPolicyToId(${input.exportName});`
      : `export const ${input.exportName}Address = lucid.utils.validatorToAddress(${input.exportName});`;

  return (
    `// Generated by aiken-devtools-mcp (tool: aiken_codegen_lucid_evolution)\n` +
    `// Package: @lucid-evolution/lucid\n\n` +
    `import type { ${importTypes} } from "@lucid-evolution/lucid";\n` +
    `// Ensure you have a Lucid instance available as "lucid" if you use the helpers below.\n\n` +
    `export const ${input.exportName}: ${asType} = {\n` +
    `  type: ${input.plutusVersion ? `"${input.plutusVersion}"` : '"PlutusV2"'},\n` +
    `  script: "${input.cborHex}",\n` +
    `};\n\n` +
    (input.includeAddressOrPolicyId ? derivationLine + "\n" : "")
  );
}
